import { Noun } from 'digital-objects'

export const Workflow = Noun('Workflow', {
  name: 'string!',
  description: 'string',
  organization: '-> Organization',
  triggerEvent: 'string!',
  steps: 'string',
  retryPolicy: 'string',
  errorHandling: 'Stop | Continue | Fallback',
  timeout: 'number',
  status: 'Draft | Active | Activated | Paused | Triggered | Archived',
  version: 'number',
  lastRunAt: 'datetime',
  runCount: 'number',
  successCount: 'number',
  failureCount: 'number',
  activate: 'Activated',
  pause: 'Paused',
  trigger: 'Triggered',
  archive: 'Archived',
})

export const Integration = Noun('Integration', {
  name: 'string!',
  slug: 'string##',
  description: 'string',
  provider: 'string!',
  providerUrl: 'string',
  providerLogo: 'string',
  category: 'Payment | CRM | Marketing | Analytics | Communication | Storage | AI | Other',
  authType: 'OAuth2 | ApiKey | Basic | Custom',
  oauthScopes: 'string',
  configSchema: 'string',
  status: 'Available | Connected | Disconnected | Synced | ComingSoon | Deprecated',
  featured: 'string',
  apiBaseUrl: 'string',
  webhookSupport: 'string',
  connect: 'Connected',
  disconnect: 'Disconnected',
  sync: 'Synced',
})

export const Agent = Noun('Agent', {
  name: 'string!',
  slug: 'string##',
  description: 'string',
  avatar: 'string',
  organization: '-> Organization',
  owner: '-> Contact',
  model: 'string',
  systemPrompt: 'string',
  instructions: 'string',
  persona: 'string',
  type: 'Assistant | Autonomous | Workflow | Specialist | Router',
  status: 'Draft | Active | Deployed | Paused | Stopped | Retired | Archived',
  visibility: 'Private | Team | Organization | Public',
  temperature: 'number',
  maxTokens: 'number',
  tools: 'string',
  functions: 'string',
  knowledgeBases: 'string',
  memory: 'None | Session | Persistent',
  memoryWindow: 'number',
  totalTokens: 'number',
  totalCost: 'number',
  averageLatency: 'number',
  successRate: 'number',
  rating: 'number',
  ratingCount: 'number',
  version: 'number',
  publishedAt: 'datetime',
  tags: 'string',
  do: 'Done',
  ask: 'Asked',
  decide: 'Decided',
  approve: 'Approved',
  notify: 'Notified',
  delegate: 'Delegated',
  escalate: 'Escalated',
  learn: 'Learned',
  reflect: 'Reflected',
  deploy: 'Deployed',
  pause: 'Paused',
  stop: 'Stopped',
  retire: 'Retired',
})
